// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MapboxController from "./mapbox_controller.js"
application.register("mapbox", MapboxController)

import SearchCarersController from "./search_carers_controller.js"
application.register("search-carers", SearchCarersController)

import StarRatingController from "./star_rating_controller.js"
application.register("star-rating", StarRatingController)
