// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// Load all the controllers within this directory and all subdirectories.
// Controller files must be named *_controller.js.

import { application } from "./application"

import MapboxController from "./mapbox_controller.js"
application.register("mapbox", MapboxController)

import SearchCarersController from "./search_carers_controller.js"
application.register("search-carers", SearchCarersController)

import StarRatingController from "./star_rating_controller.js"
application.register("star-rating", StarRatingController)

const application = Application.start()
const context = require.context("controllers", true, /_controller\.js$/)
application.load(definitionsFromContext(context))

// import Flatpickr
import { initFlatpickr } from "../plugins/flatpickr";

initFlatpickr();

// Import style for flatpickr
require("flatpickr/dist/flatpickr.css")

// Manually register Flatpickr as a stimulus controller
// application.register('flatpickr', Flatpickr)

// import a theme (could be in your main CSS entry too...)
// import 'flatpickr/dist/themes/dark.css'

